/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FollowUpRouteImport } from './routes/follow-up'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiResultRouteImport } from './routes/api/result'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminFormResponsesRouteImport } from './routes/api/admin/form-responses'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminRecruitmentRouteImport } from './routes/api/admin/recruitment'
import { Route as ApiAdminResultsRouteImport } from './routes/api/admin/results'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAdminAuthSplatRouteImport } from './routes/api/admin/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpRoute = FollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultRoute = ApiResultRouteImport.update({
  id: '/api/result',
  path: '/api/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFormResponsesRoute = ApiAdminFormResponsesRouteImport.update({
  id: '/api/admin/form-responses',
  path: '/api/admin/form-responses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRecruitmentRoute = ApiAdminRecruitmentRouteImport.update({
  id: '/api/admin/recruitment',
  path: '/api/admin/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResultsRoute = ApiAdminResultsRouteImport.update({
  id: '/api/admin/results',
  path: '/api/admin/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthSplatRoute = ApiAdminAuthSplatRouteImport.update({
  id: '/api/admin/auth/$',
  path: '/api/admin/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/follow-up': typeof FollowUpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/result': typeof ApiResultRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/form-responses': typeof ApiAdminFormResponsesRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/recruitment': typeof ApiAdminRecruitmentRoute
  '/api/admin/results': typeof ApiAdminResultsRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/auth/$': typeof ApiAdminAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/follow-up': typeof FollowUpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/result': typeof ApiResultRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/form-responses': typeof ApiAdminFormResponsesRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/recruitment': typeof ApiAdminRecruitmentRoute
  '/api/admin/results': typeof ApiAdminResultsRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/auth/$': typeof ApiAdminAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/follow-up': typeof FollowUpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/result': typeof ApiResultRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/form-responses': typeof ApiAdminFormResponsesRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/recruitment': typeof ApiAdminRecruitmentRoute
  '/api/admin/results': typeof ApiAdminResultsRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/auth/$': typeof ApiAdminAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/follow-up'
    | '/leaderboard'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/register'
    | '/api/result'
    | '/api/admin/dashboard'
    | '/api/admin/form-responses'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/recruitment'
    | '/api/admin/results'
    | '/api/admin/session'
    | '/api/admin/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/follow-up'
    | '/leaderboard'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/register'
    | '/api/result'
    | '/api/admin/dashboard'
    | '/api/admin/form-responses'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/recruitment'
    | '/api/admin/results'
    | '/api/admin/session'
    | '/api/admin/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/follow-up'
    | '/leaderboard'
    | '/api/health'
    | '/api/leaderboard'
    | '/api/register'
    | '/api/result'
    | '/api/admin/dashboard'
    | '/api/admin/form-responses'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/recruitment'
    | '/api/admin/results'
    | '/api/admin/session'
    | '/api/admin/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FollowUpRoute: typeof FollowUpRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  ApiResultRoute: typeof ApiResultRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminFormResponsesRoute: typeof ApiAdminFormResponsesRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminRecruitmentRoute: typeof ApiAdminRecruitmentRoute
  ApiAdminResultsRoute: typeof ApiAdminResultsRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminAuthSplatRoute: typeof ApiAdminAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-up': {
      id: '/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof FollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/result': {
      id: '/api/result'
      path: '/api/result'
      fullPath: '/api/result'
      preLoaderRoute: typeof ApiResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/form-responses': {
      id: '/api/admin/form-responses'
      path: '/api/admin/form-responses'
      fullPath: '/api/admin/form-responses'
      preLoaderRoute: typeof ApiAdminFormResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/recruitment': {
      id: '/api/admin/recruitment'
      path: '/api/admin/recruitment'
      fullPath: '/api/admin/recruitment'
      preLoaderRoute: typeof ApiAdminRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/results': {
      id: '/api/admin/results'
      path: '/api/admin/results'
      fullPath: '/api/admin/results'
      preLoaderRoute: typeof ApiAdminResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/$': {
      id: '/api/admin/auth/$'
      path: '/api/admin/auth/$'
      fullPath: '/api/admin/auth/$'
      preLoaderRoute: typeof ApiAdminAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FollowUpRoute: FollowUpRoute,
  LeaderboardRoute: LeaderboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  ApiResultRoute: ApiResultRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminFormResponsesRoute: ApiAdminFormResponsesRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminRecruitmentRoute: ApiAdminRecruitmentRoute,
  ApiAdminResultsRoute: ApiAdminResultsRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminAuthSplatRoute: ApiAdminAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
